/**
 * WAVE 2 — 30 new personas with DIFFERENT individual tastes than wave 1.
 * Niche-first design: defined by sub-genre identity, not just archetype.
 * Each carries: bucketVotes (baseline), loves/hates keywords (live phase),
 * behavior traits (wandering, trailers, speed), and expectedTier:
 *   'elite'   — power cinephiles: would pay ₪34/mo for unlimited
 *   'starter' — casual: would pay ₪9 one-time reveal
 * Expected archetypes derived from the engine's weight math (bucket sig
 * genres × IDF × love/hate rules).
 */
const WAVE2_PERSONAS = [
  // ───── Niche specialists (hard: same archetype, different niches) ─────
  { name: 'W2 Parody Connoisseur (26, m)', expected: 'The Cinematic Edge-Lord',
    bucketVotes: { horror2: 5, comedy: 5, horror: 4, drama: 1 },
    loves: ['parody', 'spoof', 'פארודיה'], hates: ['serious', 'רציני'],
    tier: 'elite', behavior: { trailerFocus: true } },
  { name: 'W2 Supernatural-Only Believer (44, f)', expected: 'The Cinematic Edge-Lord',
    bucketVotes: { horror: 5, mystery: 4, horror2: 2, comedy: 1 },
    loves: ['haunted', 'possession', 'exorcism', 'רוח'], hates: ['slasher', 'gore'],
    tier: 'elite', behavior: {} },
  { name: 'W2 Found-Footage Hunter (21, m)', expected: 'The Cinematic Edge-Lord',
    bucketVotes: { horror: 5, horror2: 5, romance: 1, family: 1 },
    loves: ['found footage', 'paranormal'], hates: ['cgi'],
    tier: 'starter', behavior: { fastClicker: true } },
  { name: 'W2 Heist Architect (39, m)', expected: 'The Action Junkie',
    bucketVotes: { crime: 5, action: 5, scifi: 3, romance: 1 },
    loves: ['heist', 'שוד', 'con'], hates: ['musical'],
    tier: 'elite', behavior: {} },
  { name: 'W2 Noir Detective Soul (57, f)', expected: 'The Escapist',
    bucketVotes: { mystery: 5, crime: 3, drama: 3, comedy: 1 },
    loves: ['noir', 'detective', 'בלש'], hates: ['superhero'],
    tier: 'elite', behavior: { slowReader: true } },
  { name: 'W2 Time-Loop Obsessive (30, f)', expected: 'The Escapist',
    bucketVotes: { scifi: 5, space: 5, horror: 1 },
    loves: ['time travel', 'time loop', 'מסע בזמן'], hates: ['historical'],
    tier: 'elite', behavior: {} },
  { name: 'W2 Kaiju Monster Fan (33, m)', expected: 'The Cinematic Edge-Lord',
    bucketVotes: { horror: 5, horror2: 4, action: 4, romance: 1 },
    loves: ['monster', 'kaiju', 'מפלצת', 'godzilla'], hates: ['רומנטי'],
    tier: 'starter', behavior: { trailerFocus: true } },
  { name: 'W2 Musical Theater Kid (19, f)', expected: 'The Hopeless Romantic',
    bucketVotes: { romance: 5, family: 4, action: 1, horror: 1 },
    loves: ['musical', 'מחזמר', 'dance', 'singing'], hates: ['war', 'מלחמה'],
    tier: 'starter', behavior: {} },
  { name: 'W2 True-Crime Documentary Nerd (48, f)', expected: 'The Pretentious Cinephile',
    bucketVotes: { drama: 5, mystery: 4, comedy: 1, scifi: 1 },
    loves: ['true story', 'based on', 'תיעודי'], hates: ['fantasy', 'פנטזיה'],
    tier: 'elite', behavior: { slowReader: true } },
  { name: 'W2 Sports Underdog Junkie (36, m)', expected: 'The Pretentious Cinephile',
    bucketVotes: { drama: 5, comedy: 3, horror: 1, romance: 2 },
    loves: ['boxing', 'sports', 'underdog', 'אגרוף'], hates: ['חלל', 'space'],
    tier: 'starter', behavior: {} },

  // ───── Cross-genre hybrids (hard: two competing axes) ─────
  { name: 'W2 Rom-Zom-Com Weirdo (27, f)', expected: 'The Cinematic Edge-Lord',
    bucketVotes: { horror2: 5, horror: 4, romance: 4, comedy: 4, drama: 1 },
    loves: ['zombie', 'זומבי'], hates: ['period drama'],
    tier: 'elite', behavior: {} },
  { name: 'W2 Sci-Fi Romantic (31, m)', expected: 'The Escapist',
    bucketVotes: { scifi: 5, space: 5, romance: 4, crime: 1 },
    loves: ['love', 'אהבה'], hates: ['גנגסטר'],
    tier: 'elite', behavior: {} },
  { name: 'W2 Action Mom (38, f)', expected: 'The Action Junkie',
    bucketVotes: { action: 5, crime: 4, family: 4, horror: 1 },
    loves: ['rescue', 'חילוץ'], hates: ['דם', 'gore'],
    tier: 'starter', behavior: {} },
  { name: 'W2 Funny-Scary Only (23, m)', expected: 'The Cinematic Edge-Lord',
    bucketVotes: { horror2: 5, comedy: 5, drama: 1, romance: 1 },
    loves: ['dark comedy', 'קומדיה שחורה'], hates: ['melodrama'],
    tier: 'starter', behavior: { fastClicker: true } },
  { name: 'W2 Epic Historian (61, m)', expected: 'The Escapist',
    bucketVotes: { epic: 5, drama: 4, comedy: 1, scifi: 1 },
    loves: ['rome', 'medieval', 'היסטורי'], hates: ['טיקטוק'],
    tier: 'elite', behavior: { slowReader: true } },
  { name: 'W2 Anime-Adjacent Dreamer (20, f)', expected: 'The Family & Animation Enthusiast',
    bucketVotes: { family: 5, scifi: 4, romance: 4, crime: 1 },
    loves: ['anime', 'studio ghibli', 'אנימה'], hates: ['reality'],
    tier: 'elite', behavior: {} },
  { name: 'W2 Spy Thriller Addict (45, m)', expected: 'The Action Junkie',
    bucketVotes: { action: 5, crime: 5, mystery: 3, family: 1 },
    loves: ['spy', 'espionage', 'ריגול', 'agent'], hates: ['מחזמר'],
    tier: 'elite', behavior: { trailerFocus: true } },
  { name: 'W2 Cozy Mystery Grandma (74, f)', expected: 'The Escapist',
    bucketVotes: { mystery: 5, romance: 3, horror: 1, action: 1 },
    loves: ['whodunit', 'agatha', 'תעלומה'], hates: ['violence', 'אלימות'],
    tier: 'starter', behavior: { slowReader: true } },

  // ───── Casuals & ages (easy-ish: weak/medium signals) ─────
  { name: 'W2 Date-Night Couple Proxy (29, m)', expected: 'The Basic Binge-Watcher',
    bucketVotes: { romance: 4, comedy: 4 }, defaultVote: 3,
    loves: [], hates: [], tier: 'starter', behavior: {} },
  { name: 'W2 Retired Teacher (70, f)', expected: 'The Basic Binge-Watcher',
    bucketVotes: { drama: 4 }, defaultVote: 3,
    loves: [], hates: [], tier: 'starter', behavior: { slowReader: true } },
  { name: 'W2 Airplane-Mode Watcher (41, m)', expected: 'The Basic Binge-Watcher',
    bucketVotes: { action: 4, comedy: 4 }, defaultVote: 3,
    loves: [], hates: [], tier: 'starter', behavior: {} },
  { name: 'W2 Soldier On Leave (21, m)', expected: 'The Action Junkie',
    bucketVotes: { action: 5, comedy: 4, crime: 4 }, defaultVote: 3,
    loves: ['קרב'], hates: [], tier: 'starter', behavior: { fastClicker: true } },
  { name: 'W2 New Oleh Learning Hebrew (35, f)', expected: 'The Basic Binge-Watcher',
    bucketVotes: { comedy: 4, romance: 3 }, defaultVote: 3,
    loves: [], hates: [], tier: 'starter', behavior: { slowReader: true } },
  { name: 'W2 Insomniac Shift Worker (52, m)', expected: 'The Basic Binge-Watcher',
    bucketVotes: { mystery: 3, horror: 3 }, defaultVote: 3,
    loves: [], hates: [], tier: 'starter', behavior: {} },

  // ───── Stress behaviors (system challengers) ─────
  { name: 'W2 Speed Demon Clicker (18, m)', expected: 'The Basic Binge-Watcher',
    bucketVotes: { action: 4 }, defaultVote: 3, fastestPace: true,
    loves: [], hates: [], tier: 'starter', behavior: { fastClicker: true } },
  { name: 'W2 Back-Button Abuser (24, f)', expected: 'The Hopeless Romantic',
    bucketVotes: { romance: 5, family: 3, horror: 1 }, backButtonChance: 0.15,
    loves: ['אהבה'], hates: [], tier: 'starter', behavior: {} },
  { name: 'W2 Never-Seen-Anything (16, f)', expected: 'The Basic Binge-Watcher',
    bucketVotes: {}, defaultVote: 3, notSeenChance: 0.55,
    loves: [], hates: [], tier: 'starter', behavior: {} },
  { name: 'W2 Trailer-Before-Everything (33, m)', expected: 'The Escapist',
    bucketVotes: { scifi: 5, space: 4, romance: 1 }, trailerEvery: true,
    loves: ['חלל'], hates: [], tier: 'elite', behavior: { trailerFocus: true } },
  { name: 'W2 Site Wanderer (28, f)', expected: 'The Family & Animation Enthusiast',
    bucketVotes: { family: 5, comedy: 4, horror: 1 }, wanderPages: 4,
    loves: ['פיקסאר'], hates: [], tier: 'starter', behavior: { wanderer: true } },
  { name: 'W2 Five-Star Enthusiast (50, m)', expected: 'The Basic Binge-Watcher',
    bucketVotes: { comedy: 4, action: 4, romance: 4, drama: 4 }, defaultVote: 4,
    loves: [], hates: [], tier: 'elite', behavior: {} },
];

module.exports = { WAVE2_PERSONAS };
